-- Migration: create requests table
-- Run this against your Supabase project once before starting the application.
-- The requests table stores tickets generated by the voice agent classifier for
-- physical_request and defer_to_operator intents.

create table if not exists requests (
  id              uuid primary key default gen_random_uuid(),
  room_number     text not null,
  intent          text not null check (intent in ('physical_request', 'defer_to_operator')),
  department      text not null,
  summary         text not null,
  urgency         text not null default 'medium' check (urgency in ('low', 'medium', 'high')),
  language_detected text not null default 'en',
  requires_human  boolean not null,
  status          text not null default 'open' check (status in ('open', 'in_progress', 'resolved')),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- Index for the staff dashboard query pattern (filter by status + department)
create index if not exists requests_status_department_idx
  on requests (status, department, created_at desc);

-- Enable Supabase Realtime so the staff dashboard receives live updates
alter publication supabase_realtime add table requests;
